# Generated by Django 5.0.2 on 2024-02-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
